### ISSUE TITLE
Compilation for checks started failing

### ISSUE THREAD

**Issue by sophie-h** [obi1kenobi/cargo-semver-checks#1268]
### Steps to reproduce the bug with the above code

Calling

```
$ cargo semver-checks -v -p libglycin -p libglycin-gtk4 --baseline-rev 1.1.0
```

In https://gitlab.gnome.org/GNOME/glycin, causes the following build errors

### Actual Behaviour

```
$ cargo semver-checks -v -p libglycin -p libglycin-gtk4 --baseline-rev 1.1.0
     Cloning 1.1.0
    Updating crates.io index
     Locking 167 packages to latest compatible versions
    Building libglycin v1.1.0-alpha (current)
    Checking glycin v2.2.0-alpha (/home/herold/Projects/glycin/glycin)
error[E0277]: the trait bound `std::option::Option<&[u8]>: From<&Arc<std::vec::Vec<u8>>>` is not satisfied
   --> /home/herold/Projects/glycin/glycin/src/api_common.rs:192:74
    |
192 |     let (content_type, unsure) = gio::content_type_guess(None::<String>, &head);
    |                                  -----------------------                 ^^^^^ the trait `From<&Arc<std::vec::Vec<u8>>>` is not implemented for `std::option::Option<&[u8]>`
    |                                  |
    |                                  required by a bound introduced by this call
    |
    = note: required for `&Arc<std::vec::Vec<u8>>` to implement `Into<std::option::Option<&[u8]>>`
note: required by a bound in `content_type_guess`
   --> /home/herold/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/gio-0.20.10/src/content_type.rs:12:16
    |
10  | pub fn content_type_guess<'a>(
    |        ------------------ required by a bound in this function
11  |     filename: Option<impl AsRef<std::path::Path>>,
12  |     data: impl Into<Option<&'a [u8]>>,
    |                ^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `content_type_guess`
help: consider dereferencing here
    |
192 |     let (content_type, unsure) = gio::content_type_guess(None::<String>, &**head);
    |                                                                           ++

error[E0277]: the trait bound `std::option::Option<&[u8]>: From<&Arc<std::vec::Vec<u8>>>` is not satisfied
   --> /home/herold/Projects/glycin/glycin/src/api_common.rs:208:75
    |
208 |             let content_type_fn = gio::content_type_guess(Some(filename), &head).0;
    |                                   -----------------------                 ^^^^^ the trait `From<&Arc<std::vec::Vec<u8>>>` is not implemented for `std::option::Option<&[u8]>`
    |                                   |
    |                                   required by a bound introduced by this call
    |
    = note: required for `&Arc<std::vec::Vec<u8>>` to implement `Into<std::option::Option<&[u8]>>`
note: required by a bound in `content_type_guess`
   --> /home/herold/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/gio-0.20.10/src/content_type.rs:12:16
    |
10  | pub fn content_type_guess<'a>(
    |        ------------------ required by a bound in this function
11  |     filename: Option<impl AsRef<std::path::Path>>,
12  |     data: impl Into<Option<&'a [u8]>>,
    |                ^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `content_type_guess`
help: consider dereferencing here
    |
208 |             let content_type_fn = gio::content_type_guess(Some(filename), &**head).0;
    |                                                                            ++

For more information about this error, try `rustc --explain E0277`.
error: could not compile `glycin` (lib) due to 2 previous errors
error: running cargo-doc on crate libglycin v1.1.0-alpha failed, see stderr output above
note: this is usually due to a compilation error in the crate,
      and is unlikely to be a bug in cargo-semver-checks
note: the following command can be used to reproduce the compilation error:
      cargo new --lib example &&
          cd example &&
          echo '[workspace]' >> Cargo.toml &&
          cargo add --path /home/herold/Projects/glycin/libglycin &&
          cargo check
```

### Expected Behaviour

Since this works with rust 1.86 and the crate itself, actually can be built, I expect this to be a bug *somewhere*. Since I have no clue where, I'm starting here.

### Generated System Information

System information:
-------------------
#### Software version

cargo-semver-checks 0.41.0

#### Operating system

- OS: Linux (Debian GNU/Linux)
- Kernel: 6.7.12-amd64

#### Command-line

```bash
/home/herold/.cargo/bin/cargo-semver-checks semver-checks --bugreport 
```

#### cargo version

```
> cargo -V 
cargo 1.87.0 (99624be96 2025-05-06)
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

Cargo build configuration:
--------------------------
[build]
target-dir = "/home/herold/.cargo-target"

**Comment by sophie-h** [comment]
I first thought this happened with the Rust 1.87 update, but that doesn't seem to be the case? I am at a complete loss what is suddenly causing that.

This also started happening on my build server. `cargo doc` or `cargo build` work completely fine for the same code.

**Comment by sophie-h** [comment]
I was not expecting semver-checks to ignore Cargo.lock files, to actually my issue is #991.
