### ISSUE TITLE
lint for edition

### ISSUE THREAD

**Issue by practicalrs** [obi1kenobi/cargo-semver-checks#1094]
Hi,

As I wrote in Twitter DM I've found such a situation:
- a project that uses edition 2015
- a library that uses edition 2018
- the project doesn't see the library

Here is a repo
https://github.com/practicalrs/edition-test

```sh
 cargo run
   Compiling test-bin v0.1.0 (/home/michal/projects/edition-test/test-bin)
error[E0432]: unresolved import `test_lib`
 --> src/main.rs:1:5
  |
1 | use test_lib::add;
  |     ^^^^^^^^ you might be missing crate `test_lib`
  |
help: consider importing the `test_lib` crate
  |
1 + extern crate test_lib;
  |

For more information about this error, try `rustc --explain E0432`.
error: could not compile `test-bin` (bin "test-bin") due to 1 previous error
```

When I update an edition in test-bin to 2018 it works just fine

```sh
 cargo run
   Compiling test-bin v0.1.0 (/home/michal/projects/edition-test/test-bin)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/test-bin`
Hello, world!
4
```

So IMO it would be cool to say to the crate author that he needs to bump at least a minor version when switching editions because projects that are using such a crate can not update to a newer version until they migrate to the new edition. And that may cause problems when a possible security issue is fixed.

Best regards,
Michal

**Comment by practicalrs** [comment]
OTOH it also may be a compiler problem.

**Comment by obi1kenobi** [comment]
This is before I started using Rust, but someone I chatted with mentioned that in edition 2015, `extern crate` declarations were required for all dependencies. This became unnecessary in edition 2018, and if accurate would explain the error here.

Could you try reproducing the same breakage with edition 2018 and 2021, to see if it's related to that quirk of edition 2015?

**Comment by practicalrs** [comment]
You are right. I did the initial test with serde and I did not think about checking other editions.
